"""Add Account model and link to Income

Revision ID: 2280486f130e
Revises: d9f3bf3397f0
Create Date: 2025-10-17 08:55:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2280486f130e'
down_revision = 'd9f3bf3397f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### Manually adjusted migration ###

    # Step 1: Create the new 'accounts' table
    accounts_table = op.create_table('accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)

    # Step 2: Insert a default "Main Account" so existing incomes have something to link to.
    op.bulk_insert(accounts_table,
        [
            {'id': 1, 'name': 'Main Account'},
        ]
    )

    # Step 3: Add the new 'account_id' column to the 'incomes' table.
    # We will give it a temporary default value of 1.
    op.add_column('incomes', sa.Column('account_id', sa.Integer(), nullable=False, server_default='1'))

    # Step 4: Remove the temporary server_default.
    # From now on, new entries must provide an account_id explicitly.
    op.alter_column('incomes', 'account_id', server_default=None)

    # ### end of adjustment ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'account_id')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###